### ISSUE TITLE
Improve test suite

### ISSUE THREAD

**Issue by danielfromearth** [nasa/ncompare#12]
The test suite is missing checks on the layout of the output, such as whether variables are being included or excluded from the output and how differences within each group appear.

**Comment by danielfromearth** [comment]
Yep, @kokroo, exactly. I will work next on creating a good (and small-sized) sample file(s) to include as a reference, and hopefully for use in an automated test too.

In the meantime, if you are looking for netCDF files to test, one option could be to download a couple from Earthdata https://search.earthdata.nasa.gov/search.  Of course, there are plenty of other sources of netCDF files, but that has lots of different types and so it could provide many different, and perhaps difficult, test cases.  (If you do test it with some of those files, I'd really love to hear about what you use and how it goes).

**Comment by danielfromearth** [comment]
@kokroo, I just added (in PR #15) to the `develop` branch a test that checks the text file output against a pre-generated "golden file".  When you have a chance, I think it would be good for you to try updating your feature branch with the latest in `develop`, and then updating the code as necessary so it passes the new tests. How does that sound?

**Comment by kokroo** [comment]
@danielfromearth Hello Daniel, thank you so much for creating these.
I will try to get it done in 1-3 days.

**Comment by danielfromearth** [comment]
Closing this to make a new release with the latest, and I'm going to upload it to PyPI.

If the tests present new problems, we can create a new issue.

**Comment by kokroo** [comment]
> Closing this to make a new release with the latest, and I'm going to upload it to PyPI.
> 
> If the tests present new problems, we can create a new issue.

@danielfromearth 
Hello Daniel, sorry, I got caught up with real life and could not get back on this timely. Regarding PRs, I just read this ( https://github.com/nasa/radbelt/issues/47#issuecomment-1769542636) on another NASA repo. I am still glad to submit PRs but I just wanted to give you a heads-up and confirm if you can accept them.

Thanks!

**Comment by danielfromearth** [comment]
Hi @kokroo, no worries!  This is a good question about PRs — I'm looking further into it now, and am hoping to have more information about it by late next week.

**Comment by danielfromearth** [comment]
Hi @kokroo, I've spoken with several NASA folks and it seems there is no issue with external collaborators contributing to a NASA repository licensed with the NASA Open Source Agreement (NOSA). Such contributions are very much welcome! 

The few things to still note are from this [Wikipedia page describing NOSA](https://en.wikipedia.org/wiki/NASA_Open_Source_Agreement#Reception): NOSA is "approved as an [open source license](https://en.wikipedia.org/wiki/Open_source_license) by the [Open Source Initiative](https://en.wikipedia.org/wiki/Open_Source_Initiative) (OSI)", and NOSA apparently expects each contribution to be an "original creation".

**Comment by kokroo** [comment]
> Hi @kokroo, I've spoken with several NASA folks and it seems there is no issue with external collaborators contributing to a NASA repository licensed with the NASA Open Source Agreement (NOSA). Such contributions are very much welcome!
> 
> The few things to still note are from this [Wikipedia page describing NOSA](https://en.wikipedia.org/wiki/NASA_Open_Source_Agreement#Reception): NOSA is "approved as an [open source license](https://en.wikipedia.org/wiki/Open_source_license) by the [Open Source Initiative](https://en.wikipedia.org/wiki/Open_Source_Initiative) (OSI)", and NOSA apparently expects each contribution to be an "original creation".

@danielfromearth Thank you so much for following up on this Daniel. I can send in my PRs now!

@lpsinger Radbelt is also under NOSA if I am not wrong and Daniel here received information that it's okay to accept contributions. I am really confused now since OnAIR asked me for a contributor agreement. What gives? :D

**Comment by lpsinger** [comment]
At least at my NASA center (Goddard), for software that is released under NOSA, the lawyers require us to collect hand-signed contributor license agreements from external contributors, and they have to process and approve the contributor license agreements. I have attempted this process several times over the past few years, and in not one instance has Goddard's legal counsel ever approved and processed a contributor license agreement for one of my projects.

This package may be different because it looks like it was released at Langley, and they may have more tractable lawyers there.

**Comment by danielfromearth** [comment]
Hi @kokroo, sorry for the delay in responding. You and @lpsinger have brought up some important questions that I haven't yet received clear guidance about, so I'm looking into this further and am waiting to hear confirmation of the approach that my NASA center (Langley) follows. Will let you know as soon as I know!

**Comment by danielfromearth** [comment]
Hi @kokroo, so I've gotten some unfortunate news. As of now, the Langley Research Center does require a signed Contributor License Agreement as well.  I haven't found out what exactly that looks like, so I will try to find out more about that now.

**Comment by kokroo** [comment]
@danielfromearth 
Hey Daniel, thanks for following up on this!
The amazing folks handling OnAIR at https://github.com/nasa/OnAIR/ have all of that setup already, perhaps they could guide you in the right direction?

**Comment by danielfromearth** [comment]
Thanks @kokroo, for pointing out the OnAIR repository, that's helpful.  Sorry again for the delay. I am still working to get answers to all the questions that need to addressed for Langley regarding CLAs, but I'll keep providing further updates as I get them!

**Comment by kokroo** [comment]
@danielfromearth Hello Daniel, I hope you are doing well.

Any updates on this situation?
I have prepared a new PR!

**Comment by danielfromearth** [comment]
Hi @kokroo, yes — as tracked in [this issue](https://github.com/nasa/ncompare/issues/184), the license for `ncompare` is now Apache License 2.0, so please go ahead and open the new PR!
