### ISSUE TITLE
How do I run tests on this repo?

### ISSUE THREAD

**Issue by kokroo** [nasa/ncompare#2]
I would like to add a PR for performance improvements but I also need to make sure the tests aren't breaking.
Is there a command to run the tests?

**Comment by danielfromearth** [comment]
Hi @kokroo, I just added a GitHub Actions workflow (in PR #4) that should run the tests for new PRs.

You can also run the tests at the command line.  If pytest is already in your active environment, you should be able to simply run `pytest tests`.  Or, with poetry set up, you could run `poetry run pytest tests`.

**Comment by kokroo** [comment]
Hello @danielfromearth 
Thank you for guiding me!
I have already opened a PR with performance improvements but I don't see GitHub running tests on it. Is it because I opened it before you merged PR #4?

**Comment by kokroo** [comment]
Hello @danielfromearth
Thank you for guiding me!
I have already opened a PR with performance improvements but I don't see GitHub running tests on it. Is this expected?

**Comment by danielfromearth** [comment]
@kokroo: That sounds expected — that the automated test workflow won't run until the code is on a 'feature/' branch.  
In the meantime, can you run the tests locally? 
I'll also see if there's another way for me to trigger the lint+test workflow on your PR, without having it auto-run excessively on non-feature branches.

**Comment by kokroo** [comment]
@danielfromearth I ran tests after every commit I made. So far I've seen an overall 8-16% speed increase by averaging 100 runs.

I'll get to my laptop soon and check if tests are working for my PR on github now.

**Comment by kokroo** [comment]
<img width="1352" alt="Screenshot 2023-08-22 at 19 45 22" src="https://github.com/nasa/ncompare/assets/6683709/b1c83ef0-0e01-4897-9e0b-d5b78606466d">

@danielfromearth Looks like it will need your approval each time to run the test workflow.
I ran the tests locally and they all passed.
