### ISSUE TITLE
Fix author attr for poetry

### ISSUE THREAD

**Issue by sc0tts** [nasa/ncompare#5]
Great project here; thank you!

I attempted to install the package from a local clone of the repo using poetry.  However, I got an error about the "author" line in 'pyproject.toml' being formatted incorrectly.

I changed line 7 of pyproject.toml from:

authors = ["<daniel.kaufman@nasa.gov>"]

to:

authors = ["Daniel Kaufman <daniel.kaufman@nasa.gov>"]

And installation via poetry worked perfectly.

Fyi, the full screen-output -- without poetry's nice coloring, sadly -- of the original poetry-fail was:

$ poetry install
Installing dependencies from lock file

Package operations: 3 installs, 16 updates, 0 removals

  • Updating six (1.16.0 /home/conda/feedstock_root/build_artifacts/six_1620240208055/work -> 1.16.0)
  • Updating numpy (1.23.5 /home/conda/feedstock_root/build_artifacts/numpy_1668919096861/work -> 1.23.2)
  • Updating pyparsing (3.0.9 /home/conda/feedstock_root/build_artifacts/pyparsing_1652235407899/work -> 3.0.9)
  • Updating python-dateutil (2.8.2 /home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work -> 2.8.2)
  • Updating pytz (2022.7.1 /home/conda/feedstock_root/build_artifacts/pytz_1673864280276/work -> 2022.2.1)
  • Updating attrs (22.2.0 /home/conda/feedstock_root/build_artifacts/attrs_1671632566681/work -> 22.1.0)
  • Updating cftime (1.6.2 /home/conda/feedstock_root/build_artifacts/cftime_1666833854447/work -> 1.6.1)
  • Installing et-xmlfile (1.1.0)
  • Updating iniconfig (2.0.0 /home/conda/feedstock_root/build_artifacts/iniconfig_1673103042956/work -> 1.1.1)
  • Updating packaging (23.0 /home/conda/feedstock_root/build_artifacts/packaging_1673482170163/work -> 21.3)
  • Updating pandas (1.5.3 -> 1.4.4)
  • Updating pluggy (1.0.0 /home/conda/feedstock_root/build_artifacts/pluggy_1667232663820/work -> 1.0.0)
  • Installing py (1.11.0)
  • Updating tomli (2.0.1 /home/conda/feedstock_root/build_artifacts/tomli_1644342247877/work -> 2.0.1)
  • Updating colorama (0.4.6 /home/conda/feedstock_root/build_artifacts/colorama_1666700638685/work -> 0.4.5)
  • Updating netcdf4 (1.6.2 /home/conda/feedstock_root/build_artifacts/netcdf4_1668678824560/work -> 1.6.0)
  • Installing openpyxl (3.0.10)
  • Updating pytest (7.2.1 -> 7.1.3)
  • Updating xarray (2023.1.0 /home/conda/feedstock_root/build_artifacts/xarray_1674166302925/work -> 2022.6.0)

**Invalid author string. Must be in the format: John Smith <john@example.com>**

I have **bolded** the error statement that led me to make the correction detailed above.

Thanks again!  -Scott

**Comment by danielfromearth** [comment]
Hi @sc0tts, really glad to hear others interested in using this capability!  (And thanks for the encouraging words :) )

This error should be fixed now, after commit 07dfd8e2b0fbe4df20a26ec75ba39958caab36ab, in Pull Request #4.
