### ISSUE TITLE
Just display variables and attributes that are different

### ISSUE THREAD

**Issue by nlenssen2013** [nasa/ncompare#69]
Current functionality is displaying all variables and attributes and just highlighting the differences. Enable feature to only display differences for smaller output for many different comparisons.

**Comment by danielfromearth** [comment]
@nlenssen2013, I made some changes for this and it seemed to be working. If you have time, could you check and do a quick test of it, from the [develop](https://github.com/nasa/ncompare/tree/develop) branch?

**Comment by danielfromearth** [comment]
Although this functionality has been included, the output still shows the groups even when there are no differences between all the variables in those groups.  Perhaps this output could be improved further (in another issue)?

![temp_screenshot](https://github.com/user-attachments/assets/f0ff75a2-6718-4282-8289-36a7de3fecc7)
